mysite/blog/urls.py
from django.urls import path,re_path
from . import views

app_name='blog'
#app_name='basic_app'

urlpatterns=[
    path('', views.PostListView.as_view(), name='list'),
    path('new/',views.PostCreateView.as_view(), name='new'),
    path(r'^(?P<pk>\d+)/comment/$',views.CommCreateView.as_view(), name='comment'),
    re_path(r'^(?P<pk>\d+)/edit/$',views.PostUpdateView.as_view(), name='edit'),
    re_path(r'^(?P<pk>\d+)/remove/$',views.PostDeleteView.as_view(), name='remove'),
    re_path(r'^(?P<pk>\d+)/$',views.PostDetailView.as_view(), name='detail'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('blog.urls',namespace='blog'))
]

mysite/blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    author = models.CharField(max_length=10)
    #name = models.CharField(max_length=256)

    title=models.CharField(max_length=50)
    text =models.CharField(max_length=255, null = True, blank = True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs = {'pk':self.pk})

class Comments(models.Model):
    author = models.CharField(max_length=10, null = True, blank = True)
    text =models.CharField(max_length=255, null = True, blank = True)
    #date_posted = models.DateTimeField(default = timezone.now)
    post = models.ForeignKey(Post, related_name='comments',on_delete=models.CASCADE)

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs = {'pk':self.pk})

mysite/blog/forms.py
from django import forms
from .models import Post,Comments

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields ='__all__'

class CommentsForm(forms.ModelForm):
    class Meta():
        model = Comments
        fields = '__all__'

mysite/blog/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect,HttpResponse
from . import models
from . import forms
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy

# Create your views here.
class PostCreateView(CreateView):
    fields = ('author','title','text')
    model = models.Post

class PostUpdateView(UpdateView):
    fields = ('author','title')
    model = models.Post

class PostDeleteView(DeleteView):
    #context_object_name='post'
    model = models.Post
    success_url = reverse_lazy('blog:list')

class CommCreateView(CreateView):
    fields = ['text']
    model = models.Comments

    """def post_add_tags(request):
    #post= get_object_or_404(Post, pk=pk)
        if request.method == "POST":
            form = CommentsForm(request.POST)
            if form.is_valid():
                tag = form.save(commit=False)
                tag.post= post
                tag.save()
                return redirect("single_post_view", pk=post.pk)
        else:
            form = CommentsForm()
            return render(request, "comments_form.html", {"form": form})"""


class PostDetailView(DetailView):
    context_object_name='post_detail'
    model = models.Post
    template_name = 'blog/post_detail.html'

class PostListView(ListView):
    context_object_name = 'post_list'
    model = models.Post
    template_name = 'blog/post_list.html'

mysite/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <ul>
      <li><a href ="{% url 'blog:list' %}"> My Tech blog </a></li>
      <li><a href ="{% url 'blog:new' %}"> New Post </a></li>
      <li><a href ="{% url 'admin:index' %}"> Admin </a></li>
    </ul>


    {% block body_block %}

    {% endblock %}
  </body>
</html>

mysite/blog/templates/blog/comments_form.html
{% extends "blog/base.html" %}
{% block body_block %}
<h1>
  {% if form.instance.pk %}
  Edit the Comment:
  {% else %}
  New Comment:
  {% endif %}
</h1>
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="" value="submit">
  </form>
{% endblock %}

mysite/blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

  {% block body_block %}
    <h1>
        Delete {{post.title}}?
    </h1>
    <form class="" action="" method="post">
      {% csrf_token %}
      <input type="submit" name="" value="Delete">
      <a href="{% url 'blog:detail' pk=post.pk %}">Cancel</a>
    </form>
  {% endblock %}

mysite/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}


  {% block body_block %}
    <h1>My Great Post</h1>
    <p>Name: {{post_detail.author}}</p>
    <p>Principal: {{post_detail.title}}</p>
    <p>Location: {{post_detail.text}}</p>


    <div class="">
      <p>
          <a href="{% url 'blog:edit' post_detail.pk %}">Edit</a>


          <a href="{% url 'blog:remove' post_detail.pk %}">Delete</a>
      </p>
    </div>
    <h2> comments:</h2>
    {% for comment in post_detail.comments.all %}
      <p>{{comment.author}}:
      {{comment.text}}</p>
    {% endfor %}
    <form class="" action="{% url 'blog:comment' post_detail.pk %}" method="post">
      {% csrf_token %}
      <input type="submit" name="" value="Add comment">
    </form>
{% endblock %}

mysite/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}


{% block body_block %}
<h1>
  {% if form.instance.pk %}
  Edit the post:
  {% else %}
  New Post:
  {% endif %}
</h1>
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="" value="submit">
  </form>
{% endblock %}

mysite/blog/templates/blog/post_list.html
{% extends "blog/base.html" %}


{% block body_block %}
<h1>News</h1>
<ul>
    {% for post in post_list %}
    <h2><li><a href="{{post.id}}">{{post.title}}</a></li></h2>

    {% endfor %}
</ul>
{% endblock %}